import type { GameCategory } from '../game-types';

export type CharacterFact = {
  /** OW：重装 / 输出 / 支援；SF6：格斗流派或打法定位 */
  role?: string;
  /** 武器或攻击方式描述 */
  weapon?: string;
  /** 国籍 / 出生地 */
  country?: string;
  /** 玩法定位 / 格斗风格 */
  style?: string;
  aliases?: string[];
  facts?: string;
};

/**
 * 本地角色知识库。由 `scripts/fetch-wiki.mjs` 从 fandom wiki 生成并合并到此文件。
 * 覆盖不到的角色会回退到 AI 现场生成事实，因此不会破坏任何对局。
 */
export const knowledge: Record<
  GameCategory,
  Record<string, CharacterFact>
> = {
  overwatch: {
    Ana: {
      role: '支援',
      weapon: '生物步枪（开镜即时命中，不开镜为投射物）',
      country: '埃及',
      style: '远程狙击治疗',
      aliases: ['安娜', '安那', 'Ana'],
      facts: '能治疗队友、禁疗敌人；有睡眠针和纳米激素大招。',
    },
    Ashe: {
      role: '输出',
      weapon: '半自动步枪（开镜为即时命中）',
      country: '美国',
      style: '中远程枪手',
      aliases: ['艾什', '艾许', 'Ashe'],
      facts: '可召唤智械 B.O.B. 助战；有炸药投掷。',
    },
    Baptiste: {
      role: '支援',
      weapon: '三连发步枪（即时命中）',
      country: '海地',
      style: '中程治疗输出',
      aliases: ['巴蒂斯特', '巴蒂', 'Baptiste'],
      facts: '能发射治疗榴弹；不朽力场可保队友不死；有增幅矩阵。',
    },
    Bastion: {
      role: '输出',
      weapon: '机枪（哨兵模式火力极强）',
      country: '智械',
      style: '固定火力输出',
      aliases: ['堡垒', '巴斯提恩', 'Bastion'],
      facts: '可变形的智械；有炮台哨兵模式与坦克终极技。',
    },
    Brigitte: {
      role: '支援',
      weapon: '近战连枷',
      country: '瑞典',
      style: '近战护盾辅助',
      aliases: ['布里吉塔', '碧姬', 'Brigitte'],
      facts: '莱因哈特的教女；有护盾与被动治疗光环。',
    },
    Cassidy: {
      role: '输出',
      weapon: '左轮手枪（即时命中）',
      country: '美国',
      style: '中程枪手',
      aliases: ['卡西迪', '麦卡利', 'McCree', 'Cassidy'],
      facts: '前黑爪成员；有翻滚和磁性手雷。',
    },
    'D.Va': {
      role: '重装',
      weapon: '双管融合炮与近战机甲',
      country: '韩国',
      style: '机动副坦',
      aliases: ['D.Va', 'DVA', 'DVa', '哈娜', '宋哈娜'],
      facts: '驾驶员宋哈娜；机甲可自爆，本体可脱出。',
    },
    Doomfist: {
      role: '重装',
      weapon: '拳套（近战为主）',
      country: '尼日利亚',
      style: '近战爆发重装',
      aliases: ['末日铁拳', '铁拳', 'Doomfist'],
      facts: '蓄力火箭拳造成高伤害；有位移与格挡。',
    },
    Echo: {
      role: '输出',
      weapon: '能量弹与激光（投射物）',
      country: '智械',
      style: '空中机动输出',
      aliases: ['回声', '艾可', 'Echo'],
      facts: '会飞行的智械；终极技可复制一名敌人英雄。',
    },
    Freja: {
      role: '输出',
      weapon: '弩（投射物）',
      country: '丹麦',
      style: '中远程射手',
      aliases: ['芙蕾雅', 'Freja'],
      facts: '使用连弩与抓钩机动的新输出英雄。',
    },
    Genji: {
      role: '输出',
      weapon: '手里剑（投射物）',
      country: '日本',
      style: '高机动刺客（狗位）',
      aliases: ['源氏', '源义', 'Genji'],
      facts: '半藏的弟弟；会二段跳、爬墙、反弹；终极技龙刃近战。',
    },
    Hanzo: {
      role: '输出',
      weapon: '弓箭（投射物）',
      country: '日本',
      style: '中远程射手',
      aliases: ['半藏', 'Hanzo'],
      facts: '源氏的哥哥；有散射箭、音波箭与龙魂大招。',
    },
    Hazard: {
      role: '重装',
      weapon: '近战与霰射',
      country: '苏格兰',
      style: '突进重装',
      aliases: ['哈扎德', 'Hazard'],
      facts: '会用尖刺与近身压制的新重装英雄。',
    },
    Illari: {
      role: '支援',
      weapon: '太阳能步枪（即时命中）',
      country: '秘鲁',
      style: '输出型辅助',
      aliases: ['伊拉锐', '伊拉里', 'Illari'],
      facts: '有治疗塔；终极技为太阳爆发。',
    },
    'Junker Queen': {
      role: '重装',
      weapon: '霰弹枪与飞斧',
      country: '澳大利亚',
      style: '近战吸血重装',
      aliases: ['渣客女王', '容克女王', 'Junker Queen'],
      facts: '有战吼、飞斧回血与禁疗的利刃。',
    },
    Junkrat: {
      role: '输出',
      weapon: '榴弹发射器（投射物）',
      country: '澳大利亚',
      style: '范围爆破输出',
      aliases: ['狂鼠', '路霸的老搭档', 'Junkrat'],
      facts: '有地雷、陷阱与遥控炸弹轮胎大招。',
    },
    Juno: {
      role: '支援',
      weapon: '治疗爆能枪（即时命中）',
      country: '火星',
      style: '机动辅助',
      aliases: ['朱诺', 'Juno'],
      facts: '火星殖民地出身；有滑翔机动与轨道射线大招。',
    },
    Kiriko: {
      role: '支援',
      weapon: '苦无（投射物）',
      country: '日本',
      style: '灵巧辅助',
      aliases: ['雾子', '桐子', 'Kiriko'],
      facts: '能瞬移到队友身边；有净化队友的符咒。',
    },
    Lifeweaver: {
      role: '支援',
      weapon: '花瓣能量（治疗与伤害）',
      country: '泰国',
      style: '功能型辅助',
      aliases: ['生命之梭', '织命', 'Lifeweaver'],
      facts: '有生命之握拉队友、花瓣平台抬升与治疗树。',
    },
    Lúcio: {
      role: '支援',
      weapon: '音速枪（投射物）',
      country: '巴西',
      style: '光环辅助',
      aliases: ['卢西奥', '卢西欧', 'Lucio', 'Lúcio'],
      facts: '能滑墙；在治疗与加速光环间切换；有音障护盾。',
    },
    Mauga: {
      role: '重装',
      weapon: '双管重机枪（即时命中）',
      country: '萨摩亚',
      style: '正面压制重装',
      aliases: ['毛加', '马乌加', 'Mauga'],
      facts: '双机枪齐射；有狂暴回血与冲锋。',
    },
    Mei: {
      role: '输出',
      weapon: '冷冻枪（冰锥投射物）',
      country: '中国',
      style: '控场输出',
      aliases: ['美', '周美灵', 'Mei'],
      facts: '能冰墙封路、冰封自己回血、冻结敌人。',
    },
    Mercy: {
      role: '支援',
      weapon: '治疗杖与小手枪',
      country: '瑞士',
      style: '单体治疗辅助',
      aliases: ['天使', '安吉拉·齐格勒', 'Mercy'],
      facts: '能复活队友；治疗与增伤束切换；会短暂飞行。',
    },
    Moira: {
      role: '支援',
      weapon: '生物能量（吸取与治疗）',
      country: '爱尔兰',
      style: '高续航辅助',
      aliases: ['莫伊拉', '莫伊菈', 'Moira'],
      facts: '左手治疗、右手吸取生命；有瞬移与聚合球大招。',
    },
    Orisa: {
      role: '重装',
      weapon: '聚变机枪（投射物）',
      country: '智械（努巴尼）',
      style: '抗线主坦',
      aliases: ['奥丽莎', '欧瑞莎', 'Orisa'],
      facts: '有标枪、金身减伤与重力牵引。',
    },
    Pharah: {
      role: '输出',
      weapon: '火箭炮（投射物）',
      country: '埃及',
      style: '空中轰炸输出',
      aliases: ['法老之鹰', '法拉', 'Pharah'],
      facts: '能持续飞行；有火箭弹幕大招。',
    },
    Ramattra: {
      role: '重装',
      weapon: '能量炮与近战拳头',
      country: '智械',
      style: '双形态重装',
      aliases: ['拉玛刹', '拉玛塔', 'Ramattra'],
      facts: '智械领袖；可在远程与近战形态间切换。',
    },
    Reaper: {
      role: '输出',
      weapon: '双持霰弹枪',
      country: '美国',
      style: '近战吸血输出',
      aliases: ['死神', '加布里埃尔', 'Reaper'],
      facts: '能瞬移、化为幽灵；造成伤害可吸血；死亡绽放大招。',
    },
    Reinhardt: {
      role: '重装',
      weapon: '火箭锤（近战）',
      country: '德国',
      style: '护盾主坦',
      aliases: ['莱因哈特', '大锤', 'Reinhardt'],
      facts: '有能量护盾、冲锋与裂地猛击大招。',
    },
    Roadhog: {
      role: '重装',
      weapon: '霰弹枪与钩子',
      country: '澳大利亚',
      style: '抓人重装',
      aliases: ['路霸', '路猪', 'Roadhog'],
      facts: '钩子拉近敌人；能呼吸回血；有鸡飞狗跳大招。',
    },
    Sigma: {
      role: '重装',
      weapon: '超能球（投射物）',
      country: '荷兰',
      style: '护盾重装',
      aliases: ['西格玛', '席格马', 'Sigma'],
      facts: '能吸收飞行物化为护盾；有引力大招。',
    },
    Sojourn: {
      role: '输出',
      weapon: '轨道步枪（即时命中，含充能射线）',
      country: '加拿大',
      style: '中远程枪手',
      aliases: ['索杰恩', '索洁恩', 'Sojourn'],
      facts: '有滑铲机动；充能射线可秒杀。',
    },
    'Soldier: 76': {
      role: '输出',
      weapon: '突击步枪（即时命中）',
      country: '美国',
      style: '全能枪手',
      aliases: ['士兵76', '76', '杰克·莫里森', 'Soldier 76'],
      facts: '能疾跑；有治疗立场与战术目镜自动瞄准。',
    },
    Sombra: {
      role: '输出',
      weapon: '冲锋枪（即时命中）',
      country: '墨西哥',
      style: '骇客刺客（狗位）',
      aliases: ['黑影', '桑布拉', 'Sombra'],
      facts: '能隐身、骇入敌人技能、瞬移撤离。',
    },
    Symmetra: {
      role: '输出',
      weapon: '光束与能量球（投射物）',
      country: '印度',
      style: '控场输出',
      aliases: ['秩序之光', '辛梅塔', 'Symmetra'],
      facts: '有炮塔与全队传送门。',
    },
    Torbjörn: {
      role: '输出',
      weapon: '铆钉枪与锻造锤',
      country: '瑞典',
      style: '建造输出',
      aliases: ['托比昂', '托比恩', 'Torbjörn', 'Torbjorn'],
      facts: '能造炮塔、丢护甲包；终极技熔火核心。',
    },
    Tracer: {
      role: '输出',
      weapon: '脉冲双枪（即时命中）',
      country: '英国',
      style: '高机动刺客（狗位）',
      aliases: ['猎空', '闪光', 'Tracer'],
      facts: '能闪现与时间回溯；有脉冲炸弹。',
    },
    Venture: {
      role: '输出',
      weapon: '钻头（投射物）',
      country: '加拿大',
      style: '钻地刺客（狗位）',
      aliases: ['探奇', '文图尔', 'Venture'],
      facts: '能钻入地下突袭，出土时造成范围伤害。',
    },
    Widowmaker: {
      role: '输出',
      weapon: '狙击步枪（即时命中）',
      country: '法国',
      style: '远程狙击（长枪）',
      aliases: ['黑百合', '夺命女', 'Widowmaker'],
      facts: '有抓钩位移与毒雷；爆头伤害极高。',
    },
    Winston: {
      role: '重装',
      weapon: '特斯拉炮（近程电击）',
      country: '月球出生',
      style: '机动主坦',
      aliases: ['温斯顿', '猩猩', 'Winston'],
      facts: '经基因改造的大猩猩；有跳包与屏障。',
    },
    'Wrecking Ball': {
      role: '重装',
      weapon: '双管机枪',
      country: '月球（仓鼠哈蒙德）',
      style: '机动副坦',
      aliases: ['破坏球', '仓鼠', '哈蒙德', 'Wrecking Ball'],
      facts: '仓鼠驾驶员；可变球形用钩爪高速滚动。',
    },
    Zarya: {
      role: '重装',
      weapon: '粒子炮（光束或能量球）',
      country: '俄罗斯',
      style: '护盾重装',
      aliases: ['查莉娅', '札莉雅', 'Zarya'],
      facts: '护盾吸收伤害转化为能量；有引力弹大招。',
    },
    Zenyatta: {
      role: '支援',
      weapon: '毁灭之球（投射物）',
      country: '智械（尼泊尔）',
      style: '远程输出辅助',
      aliases: ['禅雅塔', '和尚', 'Zenyatta'],
      facts: '有治疗球与增伤球；禅意大招群体治疗。',
    },
  },
  'street-fighter-6': {
    Luke: {
      role: '波升倾向',
      country: '美国',
      style: '综合格斗',
      aliases: ['卢克', 'Luke'],
      facts: '《街霸6》主役角色；近中距离压制强，有飞行道具与升龙。',
    },
    Jamie: {
      role: '强化型',
      country: '中国香港',
      style: '醉拳',
      aliases: ['杰米', 'Jamie'],
      facts: '饮酒获得强化；近身连段与突进为主。',
    },
    Manon: {
      role: '指令投',
      country: '法国',
      style: '芭蕾舞与柔道',
      aliases: ['曼侬', '玛农', 'Manon'],
      facts: '指令投成功后强化；投技型角色。',
    },
    Kimberly: {
      role: '突进压制',
      country: '美国',
      style: '忍术与跑酷',
      aliases: ['金柏莉', '金伯莉', 'Kimberly'],
      facts: '《街霸6》新角色；速度极快，多段突进。',
    },
    Marisa: {
      role: '力量型',
      country: '意大利',
      style: '拳击',
      aliases: ['玛丽莎', 'Marisa'],
      facts: '单发重拳伤害极高；有蓄力重击与铠甲。',
    },
    Lily: {
      role: '强化型',
      country: '墨西哥',
      style: '风之格斗',
      aliases: ['莉莉', 'Lily'],
      facts: '《街霸6》新角色；使用武器并借风强化。',
    },
    JP: {
      role: '牵制型',
      country: '反派组织',
      style: '能量与传送',
      aliases: ['JP'],
      facts: '《街霸6》BOSS；远程能量弹与传送牵制。',
    },
    Juri: {
      role: '突进压制',
      country: '韩国',
      style: '跆拳道',
      aliases: ['朱莉', '蛛俐', 'Juri'],
      facts: '有风破弹飞行道具；快速近身踢技。',
    },
    'Dee Jay': {
      role: '蓄力型',
      country: '牙买加',
      style: '踢拳与歌舞',
      aliases: ['迪杰', 'Dee Jay'],
      facts: '有蓄力飞行道具与突进；节奏感强。',
    },
    Cammy: {
      role: '突进压制',
      country: '英国',
      style: '军用格斗',
      aliases: ['嘉米', '凯米', 'Cammy'],
      facts: '高速突进与腿技；有螺旋箭等突进技。',
    },
    Ryu: {
      role: '波升型',
      country: '日本',
      style: '空手道',
      aliases: ['隆', '龙', 'Ryu'],
      facts: '系列主角；波动拳飞行道具、升龙拳对空。',
    },
    'E. Honda': {
      role: '蓄力/突进',
      country: '日本',
      style: '相扑',
      aliases: ['本田', 'E·本田', 'E. Honda'],
      facts: '有百裂掌与突进；相扑力士。',
    },
    Blanka: {
      role: '蓄力型',
      country: '巴西',
      style: '野兽格斗与放电',
      aliases: ['布兰卡', 'Blanka'],
      facts: '带电突进与翻滚；蓄力型角色。',
    },
    Guile: {
      role: '蓄力型',
      country: '美国',
      style: '军用格斗',
      aliases: ['古烈', '盖尔', '空军', 'Guile'],
      facts: '音速手刀飞行道具与脚刀对空；蓄力型代表。',
    },
    Ken: {
      role: '波升型',
      country: '美国',
      style: '空手道（火焰）',
      aliases: ['肯', 'Ken'],
      facts: '隆的劲敌；火焰波动拳与升龙，近身压制。',
    },
    'Chun-Li': {
      role: '波升/突进',
      country: '中国',
      style: '中国功夫与腿技',
      aliases: ['春丽', '警察', 'Chun-Li', 'Chun Li'],
      facts: '系列经典角色；有气功拳飞行道具与百裂脚。',
    },
    Zangief: {
      role: '指令投',
      country: '俄罗斯',
      style: '职业摔角',
      aliases: ['桑吉尔夫', '桑吉夫', '苏联佬', 'Zangief'],
      facts: '指令投威力巨大；摔角型角色。',
    },
    Dhalsim: {
      role: '牵制型',
      country: '印度',
      style: '瑜伽格斗',
      aliases: ['达尔西姆', '塔尔斯姆', '瑜伽', 'Dhalsim'],
      facts: '长肢牵制；有飞行道具与瞬移。',
    },
    Rashid: {
      role: '突进压制',
      country: '中东（阿联酋）',
      style: '风之格斗',
      aliases: ['拉希德', '拉希多', 'Rashid'],
      facts: '借风快速突进；机动性极强。',
    },
    'A.K.I.': {
      role: '突进/毒',
      country: '中国',
      style: '毒爪格斗',
      aliases: ['阿鬼', 'AKI', 'A.K.I.'],
      facts: '《街霸6》新角色；用毒与长爪牵制。',
    },
    Ed: {
      role: '波升/牵制',
      country: '德国',
      style: '精神力量拳击',
      aliases: ['艾德', 'Ed'],
      facts: '精神力量配合拳击；有远程念力弹。',
    },
    Akuma: {
      role: '波升型（强化）',
      country: '日本',
      style: '空手道（杀意波动）',
      aliases: ['豪鬼', '阿库玛', 'Akuma'],
      facts: '波升型顶点；波动拳、升龙、瞬移，伤害高。',
    },
    'M. Bison': {
      role: '蓄力型',
      country: '泰国（反派）',
      style: '精神力量格斗',
      aliases: ['拜森', '贝加', 'Vega', 'M. Bison', '将军', '城管'],
      facts: '有精神力量突进与踩踏；蓄力型反派。',
    },
    Terry: {
      role: '波升型',
      country: '美国',
      style: '饿狼传说格斗',
      aliases: ['特瑞', '泰瑞', 'Terry'],
      facts: '《饿狼传说》联动；有能量波飞行道具与升龙。',
    },
    Mai: {
      role: '波升/牵制',
      country: '日本',
      style: '不知火流忍术',
      aliases: ['舞', '不知火舞', 'Mai'],
      facts: '有扇子飞行道具；忍术机动。',
    },
    Elena: {
      role: '蓄力/突进',
      country: '肯尼亚',
      style: '卡波耶拉',
      aliases: ['艾莲娜', 'Elena'],
      facts: '腿技与卡波耶拉舞步；有治疗必杀。',
    },
    Sagat: {
      role: '蓄力型',
      country: '泰国',
      style: '泰拳',
      aliases: ['沙加特', '萨加特', 'Sagat'],
      facts: '泰拳之王；有高波动拳与上波飞行道具。',
    },
    'C. Viper': {
      role: '蓄力/牵制',
      country: '美国',
      style: '特工格斗',
      aliases: ['毒蛇', 'C.Viper', 'C. Viper'],
      facts: '有火焰与电击技能；招式带蓄力。',
    },
    Alex: {
      role: '指令投',
      country: '美国',
      style: '职业摔角',
      aliases: ['亚历克斯', 'Alex'],
      facts: '摔角型角色；有指令投与突进。',
    },
    Ingrid: {
      role: '波升/牵制',
      country: '未知',
      style: '太阳能能量',
      aliases: ['英格丽德', 'Ingrid'],
      facts: '有太阳能能量弹飞行道具；神秘少女。',
    },
    Yasmine: {
      role: '波升/压制',
      country: '菲律宾',
      style: '爪刀（卡兰比特刀）近战压制',
      aliases: ['亚斯敏', '亚思敏', 'Yasmine', 'Yasmin'],
      facts: '菲律宾女高中生；使用爪刀；有飞行道具"回旋之牙"和对空升龙"雄鹰展翅"（可波升）；核心是"巴亚尼"强化模式，可提升机动与招式判定；近战压制强、远距离较弱。',
    },
  },
  'pokemon-151': {},
};

/**
 * 领域术语表，用于让裁判准确理解玩家的问题（例如“狗位”“即时命中”“长枪”）。
 */
export const glossary: Record<GameCategory, string> = {
  overwatch: `《守望先锋》术语：定位分为重装(Tank)、输出(Damage)、支援(Support)三类。"即时命中"(hitscan)指子弹瞬间命中、无飞行时间，代表有卡西迪、士兵76、黑百合、艾什开镜、猎空、黑影、索杰恩。"长枪"指中远距离即时命中输出，代表有黑百合、艾什、卡西迪、士兵76、索杰恩。"狗位/狗"指高机动绕后切入的刺客型输出，代表有猎空、源氏、黑影、探奇。"投射物"指子弹有飞行时间需预判，代表有法老之鹰、狂鼠、禅雅塔、源氏、半藏、安娜不开镜。"光束/激光"指持续光束，代表有查莉娅、秩序之光、莫伊拉。"近战"指近距离肉搏，代表有莱因哈特、布里吉塔、末日铁拳、拉玛刹拳头、破坏球。"主坦"指抗线开团重装，代表有莱因哈特、温斯顿、奥丽莎、拉玛刹。"副坦/机动坦"代表有D.Va、破坏球、温斯顿。"主奶"指高持续治疗，代表有安娜、莫伊拉、巴蒂斯特、雾子。"副奶/功能辅助"代表有卢西奥、禅雅塔、布里吉塔、天使。"大招/终极技能"即终极技(Ultimate)。`,
  'street-fighter-6': `《街头霸王6》术语与玩家黑话："波升型"指以飞行道具+升龙对空为核心的立回型，代表有隆、肯、豪鬼、特瑞、亚斯敏。"蓄力型"指需按住后或下蓄力的角色，代表有古烈、拜森、布兰卡、沙加特。"指令投"指需摇杆转圈输入的强力投技，代表有桑吉尔夫、曼侬、亚历克斯。"突进型/压制型"指快速近身压制，代表有嘉米、金柏莉、拉希德、朱莉、亚斯敏。"飞行道具"指远程气功弹，代表有隆、肯、春丽、古烈、沙加特、豪鬼、特瑞、舞、JP、艾德、英格丽德、达尔西姆、亚斯敏。"升龙拳"指无敌对空技，代表有隆、肯、豪鬼、特瑞、亚斯敏。玩家常用小键盘数字表示方向指令：2=下、4=左、6=右、8=上、5=回中，P=拳、K=脚；常见指令：236=下前（波动拳）、623=前下前（升龙拳）、214=后下前、28=蓄力下上（古烈脚刀、春丽倒跃脚）、46=蓄力后前（古烈手刀）、22=下下。角色外号：M.Bison（拜森/贝加）常被叫"将军""城管"，日版名 Vega；"警察"指春丽；"瑜伽"指达尔西姆；"空军"指古烈；"苏联佬"指桑吉尔夫。`,
  'pokemon-151': '',
};

/**
 * 角色性别（用于让裁判准确回答“是男/女吗”这类基础问题）。
 */
export const genders: Record<GameCategory, Record<string, string>> = {
  overwatch: {
    Ana: '女',
    Ashe: '女',
    Baptiste: '男',
    Bastion: '其他',
    Brigitte: '女',
    Cassidy: '男',
    'D.Va': '女',
    Doomfist: '男',
    Echo: '其他',
    Freja: '女',
    Genji: '男',
    Hanzo: '男',
    Hazard: '男',
    Illari: '女',
    'Junker Queen': '女',
    Junkrat: '男',
    Juno: '女',
    Kiriko: '女',
    Lifeweaver: '男',
    Lúcio: '男',
    Mauga: '男',
    Mei: '女',
    Mercy: '女',
    Moira: '女',
    Orisa: '其他',
    Pharah: '女',
    Ramattra: '其他',
    Reaper: '男',
    Reinhardt: '男',
    Roadhog: '男',
    Sigma: '男',
    Sojourn: '女',
    'Soldier: 76': '男',
    Sombra: '女',
    Symmetra: '女',
    Torbjörn: '男',
    Tracer: '女',
    Venture: '其他',
    Widowmaker: '女',
    Winston: '男',
    'Wrecking Ball': '男',
    Zarya: '女',
    Zenyatta: '其他',
  },
  'street-fighter-6': {
    Luke: '男',
    Jamie: '男',
    Manon: '女',
    Kimberly: '女',
    Marisa: '女',
    Lily: '女',
    JP: '男',
    Juri: '女',
    'Dee Jay': '男',
    Cammy: '女',
    Ryu: '男',
    'E. Honda': '男',
    Blanka: '男',
    Guile: '男',
    Ken: '男',
    'Chun-Li': '女',
    Zangief: '男',
    Dhalsim: '男',
    Rashid: '男',
    'A.K.I.': '女',
    Ed: '男',
    Akuma: '男',
    'M. Bison': '男',
    Terry: '男',
    Mai: '女',
    Elena: '女',
    Sagat: '男',
    'C. Viper': '女',
    Alex: '男',
    Ingrid: '女',
    Yasmine: '女',
  },
  'pokemon-151': {},
};
